on:
  pull_request:
    paths:
      - "**.dot"

jobs:
  digraph_to_svg_job:
    runs-on: ubuntu-latest
    name: Create svg image from digraph .dot file
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Digraph to SVG step
        id: digraph_to_svg
        uses: alexrothenberg/digraph-to-svg-action@master
